// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvMDzLfR2p7rYHlxGr2XXH4Sjnuu6aNys',
    appId: '1:727287158173:web:99092eb3c1ce0bf71ccb74',
    messagingSenderId: '727287158173',
    projectId: 'global-entry-c8373',
    authDomain: 'global-entry-c8373.firebaseapp.com',
    storageBucket: 'global-entry-c8373.appspot.com',
    measurementId: 'G-2QQ8JVBNGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG8nYrM-xxnkMt0eIII5AgNG7Qfeh989E',
    appId: '1:727287158173:android:e4aceb46a434f29e1ccb74',
    messagingSenderId: '727287158173',
    projectId: 'global-entry-c8373',
    storageBucket: 'global-entry-c8373.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyXAMYtzVLvLa0buXskcJGzMidui23hOw',
    appId: '1:727287158173:ios:13276307d75133841ccb74',
    messagingSenderId: '727287158173',
    projectId: 'global-entry-c8373',
    storageBucket: 'global-entry-c8373.appspot.com',
    iosClientId: '727287158173-m0fjirucao5en2nol6dn4toach94p211.apps.googleusercontent.com',
    iosBundleId: 'com.dropbeardevs.globalentrynotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyXAMYtzVLvLa0buXskcJGzMidui23hOw',
    appId: '1:727287158173:ios:89c45467737543661ccb74',
    messagingSenderId: '727287158173',
    projectId: 'global-entry-c8373',
    storageBucket: 'global-entry-c8373.appspot.com',
    iosClientId: '727287158173-6nn4k7lcpr3vm12tb78gnod0i5us7eh4.apps.googleusercontent.com',
    iosBundleId: 'com.dropbeardevs.globalEntryNotify',
  );
}
